name: abcsplotch
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - pip

  # Python stack
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-image
  - scikit-learn
  - h5py
  - scanpy
  - tqdm
  - seaborn
  - jax
  - jaxlib
  - pyarrow
  - ipykernel
  - jupyter_client

  # R stack
  - r-base=4.3
  - r-essentials
  - r-devtools
  - r-data.table
  - r-matrix
  - r-optparse
  - r-rstan

  # Python/R bridge
  - rpy2

  - pip:
      - -e .
